### PR TITLE
Darwin build

### LINKED ISSUE #75: Darwin build fails
Trying to build on OS X Mojave after `brew install opencv` fails:

```
$ mkdir build
$ cd build
$ cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release ..
$ make
[  1%] Building CXX object CMakeFiles/libzxing.dir/opencv/src/zxing/MatSource.cpp.o
In file included from /Users/kousu/src/zxing-cpp/opencv/src/zxing/MatSource.cpp:17:
In file included from /Users/kousu/src/zxing-cpp/opencv/src/zxing/MatSource.h:21:
In file included from /usr/local/include/opencv4/opencv2/core/core.hpp:48:
In file included from /usr/local/include/opencv4/opencv2/core.hpp:52:
/usr/local/include/opencv4/opencv2/core/cvdef.h:656:4: error: "OpenCV 4.x+ requires enabled C++11 support"
#  error "OpenCV 4.x+ requires enabled C++11 support"
...
/usr/local/include/opencv4/opencv2/core/mat.hpp:1011:52: error: no template named 'initializer_list' in namespace 'std'
    template<typename _Tp> explicit Mat(const std::initializer_list<int> sizes, const std::initializer_list<_Tp> list);
...
```

I think these are because Darwin's clang compiler isn't defaulting to C++11 fully.

### PR DESCRIPTION
**Pull request by kousu**
Fixes #75

### CODE REVIEW

**Comment by Benjamin-Dobell** [comment]
Looks good, but could I please get the OpenCV4 commit pulled out into a different PR, and preferably changed to something like:

```cpp
#if CV_MAJOR_VERSION >= 4
#ifndef CV_CAP_PROP_FRAME_WIDTH
#define CV_CAP_PROP_FRAME_WIDTH CAP_PROP_FRAME_WIDTH
#endif
#ifndef CV_BGR2GRAY
#define CV_BGR2GRAY COLOR_BGR2GRAY
#endif
#endif
```

so as to keep compatibility with OpenCV 2 & 3.

**Comment by kousu** [comment]
Hi @Benjamin-Dobell ! I split the opencv4 patches to https://github.com/glassechidna/zxing-cpp/pull/77 like you asked; I left them in this (so, this PR now depends on that PR) since I need both to get the build working on Darwin. I hope that's okay.

**Comment by kousu** [comment]
I'd say this PR is friends with #62, which is a bunch of similar patches made for Windows. If you're feeling up to merging this, can I spend some social capital on getting that merged too?

**Comment by Benjamin-Dobell** [comment]
Yikes I made a mess of the Git history. However, this should be all merged now.

**Pull request closed without merging**
